alter table SALES_CUSTOMER_FILE_DESCRIPTOR_LINK add constraint FK_SCFDL_CUSTOMER foreign key (CUSTOMER_ID) references SALES_CUSTOMER(ID);
alter table SALES_CUSTOMER_FILE_DESCRIPTOR_LINK add constraint FK_SCFDL_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
